---
title: "Updated notes"
output: html_notebook
---

The following are updated notes based on new plots generated by Benoit after May 14th meeting.

The updated plots can be found in

`~/meetingNotes/updated_plots/`

The updated plots have been made without any jitter factor so matching data points should directly overlap. Different data processors (Reed, Steele, Casault) are represented by different colour and shape points. The opacity has been lowered so multiple points overlapped are visible.


Analyzing the new plots a few new conclusions can be made



From Benoit:

* The AMO plot now looks better.

* I did a simple scaling of the old NAO data, which now better compare with the new data.  The difference that remains is explained by differences in the old data (Roger's data used mean winter NAO as D-J-F) and the new data (Peter's data use mean winter NAO as D-J-F-M).

From Catherine:

* __Would you please replot stratification without Reid's HL2-only data, and we can most likely move forward with the SS-wide values you have plotted.__

* For the zooplankton, it looks like Dan maybe used HL and Reid used HL2 (or vice-versa), while you have plotted both. Is that correct? __We will need clarification from Emily about which is needed for the for the PCA. Could you confirm which it was?__ Do you think that the other minor differences are due to data corrections, or is there something more going on there?